version: "2"

linters:
  default: fast

  # Enable specific linter.
  enable:
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    # - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    # - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl_v5
    - zerologlint

  # Disable specific linters.
  disable:
    - cyclop # 57
    - depguard # 877
    - dupl # 14
    - dupword # 45
    - exhaustruct # 69
    - forcetypeassert # 29
    - funcorder # 8
    - funlen # 32
    - gochecknoglobals # 5
    - gocognit # 10
    - goconst # 5
    - gocritic # 37
    - godot # 1052
    - gosec # 12
    - inamedparam # 9
    - intrange # 251
    - ireturn # 18
    - lll # 434
    - mnd # 232
    - nestif # 5
    - paralleltest # 715
    - testpackage # 684
    - wsl # depricated

  settings:
    revive:
      enable-all-rules: true
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: add-constant
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: function-length
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: max-control-nesting
          disabled: true
        - name: cyclomatic
          arguments: [27]
        - name: cognitive-complexity
          arguments: [41]

  # exclusions:

formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo

  # settings:
  #   gofmt:
  #     simplify: false
  #     rewrite-rules:
  #       - pattern: "interface{}"
  #         replacement: "any"
  #       - pattern: "a[b:len(a)]"
  #         replacement: "a[b:]"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true

# Options for analysis running.
run:
  timeout: 5m
  relative-path-mode: gomod
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true
