version: "2"

linters:
  default: fast

  # Enable specific linter.
  enable:
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    # - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    # - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl_v5
    - zerologlint

  # Disable specific linters.
  disable:
    - godoclint # 53 - strict doc format not needed for educational code
    - dupl # 14 - duplicate code in tests, acceptable for test data
    - dupword # 45
    - exhaustruct # 65 - requires all struct fields initialized, too strict
    - forcetypeassert # 29 - requires checked type assertions everywhere
    - funcorder # 8 - strict function ordering, not necessary
    - funlen # 39 - function length, some complex algos need longer functions
    - gochecknoglobals # 5 - global variables sometimes needed
    - gocognit # 20 - cognitive complexity, using cyclop instead
    - goconst # 5 - extract constants, too strict for test values
    - gocritic # 45 - style suggestions may conflict with algorithm clarity
    - gosec # 60 - security warnings don't apply to algorithm solutions
    - inamedparam # 9 - named parameters not always needed
    - ireturn # 4 - return interfaces, too strict
    - lll # 467 - line length, using golines formatter instead
    - mnd # 358 - magic numbers acceptable in algorithm code
    - nestif # 2 - nested if complexity, overlaps with other checks
    - paralleltest # 920 - parallel tests not always needed
    - testpackage # 895 - tests in same package for testing internals
    - wsl # deprecated

  settings:
    revive:
      enable-all-rules: true
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: add-constant
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: function-length
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: max-control-nesting
          disabled: true
        - name: cyclomatic
          arguments: [35]
        - name: cognitive-complexity
          arguments: [80]
        - name: confusing-results
          disabled: true
    gocyclo:
      min-complexity: 35
    cyclop:
      max-complexity: 35 # 10
      # package-average: 0
    depguard:
      rules:
        main:
          allow:
            - testing
            - sort
            - math
            - strings
            - container/heap
            - container/list
            - strconv
            - slices
            - bytes
            - unicode
            - fmt
            - maps
            - reflect
            - github.com/stretchr/testify/assert
            - github.com/shahzodshafizod/leetcode/pkg
    godot:
      period: false

  # exclusions:

formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo

  # settings:
  #   gofmt:
  #     simplify: false
  #     rewrite-rules:
  #       - pattern: "interface{}"
  #         replacement: "any"
  #       - pattern: "a[b:len(a)]"
  #         replacement: "a[b:]"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true

# Options for analysis running.
run:
  timeout: 5m
  relative-path-mode: gomod
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true
